const express = require('express');
const router = express.Router();
const multer = require('multer');
const { protect, ownerOnly } = require('../middleware/authMiddleware');
const { addCustomer, getCustomers, getCustomerById, updateCustomer, deactivateCustomer, resetCustomerPassword, makeVapiCall } = require('../controllers/ownerCustomerController');
const { addTransaction, getCustomerTransactions, getOwnerDashboard, getAnalytics } = require('../controllers/ownerTransactionController');
const { registerFace, recognizeFace, scanFaces } = require('../controllers/ownerFaceController');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
router.use(protect, ownerOnly);
router.post('/customers', addCustomer);
router.get('/customers', getCustomers);
router.get('/customers/:id', getCustomerById);
router.put('/customers/:id', updateCustomer);
router.delete('/customers/:id', deactivateCustomer);
router.post('/customers/:id/reset-password', resetCustomerPassword);
router.post('/customers/:id/call', makeVapiCall);
router.post('/transactions', addTransaction);
router.get('/transactions/:customerId', getCustomerTransactions);
router.get('/dashboard', getOwnerDashboard);
router.get('/analytics', getAnalytics);
router.post('/face/register/:customerId', upload.single('file'), registerFace);
router.post('/face/recognize', upload.single('file'), recognizeFace);
router.post('/face/scan', upload.single('file'), scanFaces);
module.exports = router;
