require('dotenv').config();
const express=require('express');
const cors=require('cors');
const connectDB=require('./config/db');
const {notFound,errorHandler}=require('./middleware/errorMiddleware');
const authRoutes=require('./routes/authRoutes');
const ownerRoutes=require('./routes/ownerRoutes');
const customerRoutes=require('./routes/customerRoutes');
const app=express();
const PORT=process.env.PORT||5000;
connectDB();
app.use(cors({origin:true,credentials:true}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({success:true,message:'Velox Ledger API is running',time:new Date().toISOString()}));
app.use('/api/auth',authRoutes); app.use('/api/owner',ownerRoutes); app.use('/api/customer',customerRoutes);
app.use(notFound); app.use(errorHandler);
app.listen(PORT,()=>console.log(`Velox Ledger API running on http://localhost:${PORT}`));
